### ISSUE TITLE
TODO list for Bridges

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#1345]
## Fix TODO items in code

- [x] #1543 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/bridge_optimizer.jl#L601
- [x] https://github.com/jump-dev/MathOptInterface.jl/pull/1348 <s>https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/bridge_optimizer.jl#L635-L636</s>
- [x] #1543 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/bridge_optimizer.jl#L668-L670
- [ ] https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/bridge_optimizer.jl#L1905
- [x] https://github.com/jump-dev/MathOptInterface.jl/pull/1350 <s>https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/bridge.jl#L9</s>
- [x] #1548 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/Constraint.jl#L99
- [x] #1542 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/det.jl#L1
- [x] #1544 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/geomean.jl#L49
- [x] https://github.com/jump-dev/MathOptInterface.jl/pull/1349 <s>https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/geomean.jl#L68-L69</s>
- [x] #433 https://github.com/jump-dev/MathOptInterface.jl/blob/7923c601506cba2edb44f25eca830fc74d7cfe70/src/Bridges/Constraint/scalarize.jl#L143

**Comment by odow** [comment]
Closing as sufficiently resolved or there are other issues to track. The transform question remains, but that seems lower priority, no one has asked for it, and it isn't obvious what to do.
