### ISSUE TITLE
Rewrite MOI.Test

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1398]
<s>The test names do not follow the style guide, should we rename `contlineartest` to `continuous_linear_test` ?</s>
_Edit: @odow: hijacking this issue to lay out my plan for the new MOI.Test_

## Purpose

The purpose of this issue is to track the items that need to be completed in order to rewrite our MOI.Test submodule. 

Significant progress and design was started in https://github.com/jump-dev/MathOptInterface.jl/pull/1404. But rather than continue that, I'm going to break it into smaller pieces.

## Where we are 

Our current testing regime is comprehensive, but a bit all over the place.

There's a mix of things like `MOI.Test.unittest` that wrap a whole lot of tests, and others like `MOI.Test.default_status_test` that you just need to add. Even the documentation for how to test a solver is complicated (https://github.com/jump-dev/MathOptInterface.jl/issues/224)! https://jump.dev/MathOptInterface.jl/dev/submodules/Test/overview/#How-to-test-a-solver

The current design is also bad because it's hard to add new tests. 

As evidenced by the documentation: https://jump.dev/MathOptInterface.jl/dev/submodules/Test/overview/#How-to-add-a-test, you need to write a test, then write a test for the test, and then make sure that everything works. It's hard to run a small contingent of tests, and it's hard to decide where to put a new test, and where to put the test of the test.

This also evidenced by the large number of open test issues that aren't getting addressed. These range from #470 (August 2018!) to #1201 (November 2020). If they were easier to add, it would happen quicker!

Naming and visibility of each test is also a problem: https://github.com/jump-dev/MathOptInterface.jl/issues/1029. If `linear10btest` fails, what does that mean? 

## New design

The basic design is `runtests`, a single entry point to _all_ tests in MOI.

Instead of breaking down tests by files or dictionaries, tests are normal Julia functions with descriptive names that can be excluded or included by the user.

Here's the code to test the `MockOptimizer`:
```Julia
MOI.Test.runtests(
    MOIU.MockOptimizer(MOIU.UniversalFallback(MOIU.Model{Float64}())),
    MOI.Test.Config(basis = true),
    exclude = ["test_nonlinear_"],
)
```
Much better. 

There is also a need for certain tests to modify the model prior to running the test (changing solver parameters/tolerances, for example). That can be achieved by overloading `setup_test(::typeof(f), ::MOI.ModelLike, ::MOI.Test.Config)` for the particular function `f`.

## TODO

 - [x] Rename MOI.Test to MOI.DeprecatedTest https://github.com/jump-dev/MathOptInterface.jl/pull/1407 
 - [x] Add core functionality of new MOI.Test, plus documentation (but now actual tests) https://github.com/jump-dev/MathOptInterface.jl/pull/1408  #1428 #1434 #1437

 - [x] Migrate existing tests, cleaning an clarifying naming conventions file-by-file    
    - [x] UnitTests/attributes #1410
    - [x] UnitTests/basic_constriant_tests #1415
    - [x] UnitTests/constraints #1417
    - [x] UnitTests/modifications #1413
    - [x] UnitTests/objectives #1416 #1432
    - [x] UnitTests/solve #1418 
    - [x] UnitTests/variables #1410
    - [x] contconic #1427 
    - [x] contlinear #1426 
    - [x] contquadratic #1425
    - [x] intconic #1425
    - [x] intlinear #1424 
    - [x] modellike #1419
    - [x] nlp #1423 
- [x] Migrate testing of MOI from DeprecatedTest to the new MOI.Test
   - [x] Bridges
   - [x] FileFormats #1436
   - [x] Test #1438 #1439
   - [x] Utilities #1440 #1441 #1442 #1443 #1444 #1445 #1446 #1448 #1449 #1450 #1451 #1452 #1453 #1455 #1456 #1457

**Comment by odow** [comment]
I had wanted to do a much larger refactoring of the tests, but it seemed like a lot of breakage for little gain...

**Comment by odow** [comment]
There are quite a few test-related issues, and it can be hard to make sure you run all tests.

https://github.com/jump-dev/MathOptInterface.jl/issues/224
https://github.com/jump-dev/MathOptInterface.jl/issues/307
https://github.com/jump-dev/MathOptInterface.jl/issues/1029

It's also a lot of effort to add new tests.

I wonder about having a single `Test.runtests` function with appropriately named functions that you can include/exclude based on their name.

```Julia
MOI.Test.runtests(
    optimizer, 
    config, 
    include = [
        "test_linear_",  # name -> startswith(name, "test_linear_")
    ],
    exclude = [
        r"conic",  # name -> occursin(name, r"conic")
    ],
)
```

**Comment by blegat** [comment]
I agree, we could do that if we make the tests automatically exclude themself if what's tested is not supported, instead of testing `support_constraint` and `supports` at the beginning of each test.
That way, the excluded tests will only indicate failures, an we don't need to update every solver every time we add a new test.

**Comment by odow** [comment]
I'm working on a PR that I think makes a lot more sense. Stay tuned.

**Comment by odow** [comment]
@blegat: these `get_fallback`s throw an `ArgumentError`. Shouldn't they throw `UnsupportedAttribute` instead?

https://github.com/jump-dev/MathOptInterface.jl/blob/fe19bbff08eaeb9ff8afe131bcc33e9d747c9f3f/src/attributes.jl#L299-L308

This is causing GLPK to fail the new tests because it doesn't skip unsupported attributes.

**Comment by blegat** [comment]
`UnsupportedAttribute` is when the attributes cannot be `set` and is thrown during `set` only at the moment.
I guess if `is_copyable(attr) && !supports(model, attr)` then it might make sense to throw `UnsupportedAttribute` I have not really understood the use case though.

**Comment by odow** [comment]
The main use-case is attributes set by `optimize!`. 

For example, if GLPK attempts to query ConstraintDualStart of a constraint, it falls back to this and throws `ArgumentError`. Shouldn't it more properly throw `UnsupportedAttribute`?

**Comment by odow** [comment]
For example:
```julia
julia> model = Ipopt.Optimizer()
Ipopt.Optimizer

julia> MOI.get(model, MOI.ObjectiveBound())
ERROR: ArgumentError: Ipopt.Optimizer does not support getting the attribute MathOptInterface.ObjectiveBound().
Stacktrace:
 [1] get_fallback(model::Ipopt.Optimizer, attr::MathOptInterface.ObjectiveBound)
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:303
 [2] get(::Ipopt.Optimizer, ::MathOptInterface.ObjectiveBound)
   @ MathOptInterface ~/.julia/dev/MathOptInterface/src/attributes.jl:296
 [3] top-level scope
   @ REPL[13]:1
```
This doesn't really make sense though. Is it an argument error? It'd make more sense if it threw
```julia
julia> throw(MOI.UnsupportedAttribute(MOI.ObjectiveBound()))
ERROR: MathOptInterface.UnsupportedAttribute{MathOptInterface.ObjectiveBound}: Attribute MathOptInterface.ObjectiveBound() is not supported by the model.
Stacktrace:
 [1] top-level scope
   @ REPL[14]:1
```

**Comment by blegat** [comment]
Indeed, but currently `supports` only make sense for `is_copyable` attributes.
We could extend the meaning and define it for `is_set_by_optimize` attributes. I'm all for defining `supports` in this situation as well as it would allow to fix https://github.com/jump-dev/MathOptInterface.jl/issues/1310 (we won't need `use_fallback` as the caching optimizer would be able to use `supports`).
Moreover, as shown in the table of https://github.com/blegat/JuMP-dev_2019_tutorial/blob/master/Defining%20new%20attributes.ipynb, we don't have any example of attributes that are both `is_copyable` and `is_set_by_optimize` so it shouldn't create any confusion. For `is_copyable`, supports means: can it be copied ever ? So**not** about can it be set right now in the current state of the model. For `is_set_by_optimize`, we need to decide between can it be got ever or can it be got in the current situation. What if it's supported but optimize has not been called yet ? What if it is supported but here the solution is special, e.g. infeasible, so in that case it isn't ? It would be more consistent with `is_copyable` if we make `supports` independent on the current state for `is_set_by_optimize`.

**Comment by odow** [comment]
> we need to decide between can it be got ever or can it be got in the current situation

Same as `is_copyable`: can it ever be got.

If it isn't supported in the current situation, the solver will throw an error (like it only supports ObjectiveBound or MIP problems).

**Comment by blegat** [comment]
Ok, now the question is what do we do for attributes that are neither copyable nor set by optimize, like ListOf..., do we ask support to be implemented as well?

**Comment by odow** [comment]
I think it only makes sense to define supports for optional attributes. `ListOfModelAttributes` etc aren't optional. They're a core part of the API.

**Comment by odow** [comment]
@blegat any suggestions for how to refactor the bridge testing? They currently take _forever_ to run. And there are some open issues: https://github.com/jump-dev/MathOptInterface.jl/issues/820, https://github.com/jump-dev/MathOptInterface.jl/issues/750

**Comment by blegat** [comment]
> I think it only makes sense to define supports for optional attributes. `ListOfModelAttributes` etc aren't optional. They're a core part of the API.

I don't thing there is a well-defined notion of core part of the API. Many ModelLike don't implement ListOfModelAttributesSet

**Comment by blegat** [comment]
> @blegat any suggestions for how to refactor the bridge testing? They currently take forever to run

Moving the `@testset`s to functions would be a good start, I don't have much ideas of any other improvements.

**Comment by odow** [comment]
Changing the fallback to throw `UnsupportedAttribute` isn't so simple, because they actually get captured in a a `Test.TestSetException`. That means we can't distinguish them from a standard failure like returning the wrong answer.

The work-around would be to change
```Julia
@test MOI.get(model, MOI.SolverName()) isa AbstractString
```
to
```Julia
ret = MOI.get(model, MOI.SolverName())
@test ret isa AbstractString
```
but that's pretty painful and likely to break.

The better long-term solution is to move away from `Base.Test` to https://github.com/IainNZ/Pukeko.jl, and modify the `@test` error to wrap the inner error. We should be able to modify Pukeko to also run each function on a different Julia thread for speed.

**Comment by blegat** [comment]
I don't understand, we would do that right ?
```julia
if MOI.supports(model, MOI.SolverName())
    @test MOI.get(model, MOI.SolverName()) isa AbstractString
end
```
And you want a way to avoid having to write the `if` everytime right ?
Maybe something like `test_attribute(expected_value, model, attr, args...)` that first tests with `supports` and then do the `get` ? The `isa` is more tricky but I assume it's not that common. Otherwise we can have one for `isa` as well

**Comment by odow** [comment]
Yeah:
```julia
@requires MOI.supports(model, MOI.SolverName())
```

The other approach is that we already catch and pass on `Unsupported` or `NotAllowed` errors. But the mixing with `@test` obscures this.

Extending `supports` is still on the cards.

**Comment by odow** [comment]
Okay! That was an ordeal. I'm closing this issue as complete. The "supports" thing is still unresolved, but I might leave it for now and try updating some solvers. We can open a new issue to track if it becomes a problem.
