### ISSUE TITLE
Re-factor promote_operation and operate

### ISSUE THREAD

**Issue by odow** [jump-dev/MathOptInterface.jl#2203]
There are a bunch of rules for various `promote_operation` and `operate`. 
https://github.com/jump-dev/MathOptInterface.jl/blob/6b2192a991bab65a087284fcba6493de09bf786d/src/Utilities/functions.jl#L1597-L1610
https://github.com/jump-dev/MathOptInterface.jl/blob/6b2192a991bab65a087284fcba6493de09bf786d/src/Utilities/functions.jl#L1697-L1715

Defining a new function is really hard because it requires whack-a-mole: https://github.com/jump-dev/MathOptInterface.jl/pull/2201

I think we need an explicit write up of what functions are implemented, along with tests, so that we can check everything is working as intended.

**Comment by blegat** [comment]
Yes, I added them gradually whenever one was needed by a bridge but it would be nice to have a more structured list of what's functions should implement which is useful when defining a new function and what bridges can expect functions have implemented so that you know what you can use when writing a bridge.

**Comment by odow** [comment]
I've been looking into `operate`, and it is...not fun. We have `operate` and `operate!` and `operate_term` and `map_terms!` and `operate_terms` and `operate_terms!` and `operate_output_index!`.

I haven't quite figured out a sensible approach yet.

**Comment by odow** [comment]
To update this:

 - [x] #2206 refactored promote_operation
 - [x] #2208 refactored the operate methods
 - [ ] #2212 cleaned up and merged some of the operate methods
 - [ ] #2213 is going to clean up the `Base.` overloads
 - [ ] Implement operate for `ScalarNonlinearFunction`

**Comment by odow** [comment]
Closing because this is now a lot cleaner.
